yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordResetView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(),
         name='signup'),
    path('logout/',
         LogoutView.as_view(
             template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),

]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Создание модели Group."""
    title = models.CharField(max_length=200,
                             verbose_name='Группа')
    slug = models.SlugField(max_length=50, unique=True,
                            verbose_name='URL адрес')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    """Создание модели Post."""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    """Создание формы модели Post."""
    text = forms.CharField(widget=forms.Textarea,
                           required=True,
                           label='Текст поста',
                           help_text='Текст нового поста')

    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'group': 'Группа',
        }
        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    """Форма создания пользователя."""
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PostForm
from .models import Post, Group, User

PAGINATOR_POSTS = 10


def paginator(request, posts):
    """Paginator. Вывод по 10 постов на страницу."""
    paginator = Paginator(posts, PAGINATOR_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    """Главная страница."""
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group', 'author')
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страница списка постов."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = paginator(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Страница профиля."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    page_obj = paginator(request, posts)

    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Страница публикации."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    post_author = post.author.posts.count()
    context = {
        'post': post,
        'post_author': post_author,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Страница создания публикации. Доступна если пользователь авторизован."""
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Страница редактирования публикации. Доступна если пользователь авторизован."""
    is_edit = True
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    if request.user == post.author:
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:post_detail', post.id)
        context = {
            'form': form,
            'is_edit': is_edit,
        }
        return render(request, template, context)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    """Страница регистрации пользователя."""
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->

{% load static %}

<head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} title {% endblock title %}</title>
</head>
<body>
<header>
    {% include 'includes/header.html' %}
</header>
<main>
    {% block content %}
    Контент не подвезли :(
    {% endblock %}

</main>
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->
<footer>
    {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
    <nav class="navbar navbar-light"
         style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30"
                     height="30"
                     class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
            {# Добавлено в спринте #}
            {% with request.resolver_match.view_name as view_name %}
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link
                           {% if view_name  == 'about:author' %}
                           active
                           {% endif %}"
                       href="{% url 'about:author' %}">Об авторе</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link
                            {% if view_name  == 'about:tech' %}
                            active
                            {% endif %}"
                       href="{% url 'about:tech' %}">Технологии</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                       href="{% url 'posts:post_create' %}">Новая запись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link
                               {% if view_name  == 'users:password_change' %}
                               active
                               {% endif %}"
                       href="{% url 'users:password_change' %}">
                        Изменить пароль
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link
                           {% if view_name  == 'users:logout' %}
                           active
                           {% endif %}"
                       href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li>
                    Пользователь: {{ user.username }}
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link
                               {% if view_name  == 'users:login' %}
                               active
                               {% endif %}"
                       href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link
                               {% if view_name  == 'users:signup' %}
                               active
                               {% endif %}"
                       href="{% url 'users:signup' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
            {# Конец добавленого в спринте #}
        </div>
    </nav>
</header>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}
                    Редактировать пост
                    {% else %}
                    Новый пост
                    {% endif %}
                </div>
                <div class="card-body">
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="post" action="
              {% if is_edit %}
                {% url 'posts:post_edit' form.instance.pk %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3 p-3"
                             {% if field.field.required %}
                             aria-required="true"
                             {% else %}
                             aria-required="false"
                             {% endif %}
                        >
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            <div>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Все записи группы {% endblock title %}
{% block content %}

<div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    <article>
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
    <hr>
</div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock title %}
{% block content %}

<div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">
                    все посты пользователя
                </a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d M Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        <p>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </p>
        {% endif %}
        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
    <hr>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{post.text|truncatechars:30}} {% endblock %}
{% block content %}

<div class="container py-5">
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                <li class="list-group-item">
                    Группа: {{ post.group }}
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы
                    </a>
                </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span> {{ post.author.posts.count }} </span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author.username %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p>
                {{ post.text }}
            </p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                редактировать запись
            </a>
        </article>
    </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %}

<div class="container py-5">
    <h1>
        Все посты пользователя {{ author.get_full_name }}
    </h1>
    <h3>
        Всего постов: {{ author.posts.count }}
    </h3>
    {% for post in page_obj %}
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>
        {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
</div>
<!-- под последним постом нет линии -->
{% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}

                <form method="post"
                      {% if action_url %}
                      action="{% url action_url %}"
                      {% endif %}
                >
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group row my-3"
                         {% if field.field.required %}
                         aria-required="true"
                         {% else %}
                         aria-required="false"
                         {% endif %}
                    >
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        <div>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                        <!-- Тест на внимательность. Без переопределения шаблона этого адреса
                        не существует. Нужно что-то делать, иначе все упадет -->
                        <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                            Забыли пароль?
                        </a>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}

  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_change' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}

      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}